# Generated by Django 4.1 on 2022-09-02 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='colors',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='image',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='item_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='name1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='useritem',
            name='sizes',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
